Triage docs/source/examples scripts

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -26,15 +26,32 @@ jobs:
         run: |
           sudo apt-get install libpython2.7  # required by paup
           python -m pip install --upgrade pip
+      - name: Install paup
+        run: |
+          temp_dir=$(mktemp -d)
+          wget -P ${temp_dir} http://phylosolutions.com/paup-test/paup4a168_ubuntu64.gz
+          gunzip ${temp_dir}/paup4a168_ubuntu64.gz
+          chmod +x ${temp_dir}/paup4a168_ubuntu64
+          sudo mv ${temp_dir}/paup4a168_ubuntu64 /usr/local/bin/paup
+          echo "export DENDROPY_PAUP_EXECUTABLE_PATH=/usr/local/bin/paup" >> "${GITHUB_ENV}"
       - name: Install dendropy
         run: |
           python -m pip install .
       - name: Run examples
         run: |
           cd docs/source/examples
+          # only allow known failures
+          # and enforce removal of working examples from known failures
           for f in *.py; do
             echo "${f}"
-            python3 "${f}"
+            if timeout 10 python3 "${f}" && ! grep -q "${f}" backlogged-fail-whitelist.txt; then
+              :
+            elif grep -q "${f}" backlogged-fail-whitelist.txt; then
+              :
+            else
+              break
+              exit 1
+            fi
           done
   lint:
     runs-on: ubuntu-latest
